### ISSUE TITLE
Increase codespan-lsp version range for lsp-types to < 0.75

### ISSUE THREAD

**Issue by ebkalderon** [brendanzab/codespan#234]
There has been a new release of `lsp-types` yesterday, bumping the version to 0.74 ([release](https://github.com/gluon-lang/lsp-types/releases/tag/vv0.74.0)), which includes [many fixes and improvements](https://github.com/gluon-lang/lsp-types/compare/vv0.73.0...vv0.74.0). Thankfully, it includes no changes to the `Position` nor `Range` types used by `codespan-lsp`.

I've tested compatibility of `codespan-lsp` with this new version of `lsp-types` by bumping the Cargo version range up to:

```toml
lsp-types = ">=0.70,<0.75"
```

And everything appears to compile fine. It would be nice if we could increase this version range so more downstream libraries and compilers can target the latest upcoming version of the LSP specification. This would require a new patch release of `codespan-lsp`.

**Comment by ebkalderon** [comment]
To verify that a patch release of `codespan-lsp` was sufficient and would not result in build failures, I created a dummy Cargo project with the following `main.rs` file:

```rust
use codespan::{ByteIndex, Files};
use lsp_types::Position;

fn main() {
    let mut files = Files::new();
    let id = files.add("foo", "bar");
    let _pos: Position = codespan_lsp::byte_index_to_position(&files, id, ByteIndex::from(1)).unwrap();
}
```

The project is able to compile with the following dependencies:

```toml
codespan = "0.9.2"
codespan-lsp = "0.9.2"
lsp-types = "0.73"
```

Next, I switch to my own local copies of `codespan` and `codespan-lsp` 0.9.3, which contain the `lsp-types` version range increase, like so:

```toml
codespan-lsp = { version = "0.9.3", path = "../codespan/codespan-lsp" }
codespan = { version = "0.9.3", path = "../codespan/codespan" }
lsp-types = "0.73"
```

We can confirm that Cargo sticks with `lsp-types` 0.73 to keep the project compiling.

If I select `lsp-types = "0.74"` and run `cargo update -p codespan-lsp`, Cargo successfully upgrades `lsp-types` to 0.74, and the project is still able to compile with no issues. 👍

**Comment by ebkalderon** [comment]
To verify that a patch release of `codespan-lsp` was sufficient and would not result in build failures, I created a dummy Cargo project with the following `main.rs` file:

```rust
use codespan::{ByteIndex, Files};
use lsp_types::Position;

fn main() {
    let mut files = Files::new();
    let id = files.add("foo", "bar");
    let _pos: Position = codespan_lsp::byte_index_to_position(&files, id, ByteIndex::from(1)).unwrap();
}
```

The project is able to compile with the following dependencies:

```toml
codespan = "0.9.2"
codespan-lsp = "0.9.2"
lsp-types = "0.73"
```

Next, I switch to my own local copies of `codespan` and `codespan-lsp` 0.9.3, the latter of which contains the `lsp-types` version range increase to `> 0.75`, like so:

```toml
codespan = { version = "0.9.3", path = "../codespan/codespan" }
codespan-lsp = { version = "0.9.3", path = "../codespan/codespan-lsp" }
lsp-types = "0.73"
```

We can confirm that Cargo sticks with `lsp-types` 0.73 to keep the project compiling.

If I select `lsp-types = "0.74"` and run `cargo update -p codespan-lsp`, Cargo successfully upgrades `lsp-types` to the latest version, and the project is still able to compile with no issues. 👍
